### ISSUE TITLE
get ModuleNotFoundError when running Python files in tools dictionary

### ISSUE THREAD

**Issue by LeeJZh** [YvanYin/VNL_Monocular_Depth_Prediction#32]
Traceback (most recent call last):
  File "tools/test_nyu_metric.py", line 5, in <module>
    from lib.core.config import cfg
ModuleNotFoundError: No module named 'lib'

Traceback (most recent call last):
  File "./tools/train_nyu_metric.py", line 1, in <module>
    from data.load_dataset import CustomerDataLoader
ModuleNotFoundError: No module named 'data'

**Comment by YvanYin** [comment]
Hi, you should add the PYTHONPATH of this project.
