### ISSUE TITLE
Error when running train_kitti_metric.py

### ISSUE THREAD

**Issue by Tocmac** [YvanYin/VNL_Monocular_Depth_Prediction#66]
Hello, when I try to run train_kitti_metric.py, I got an error like this.
```
----------------- End -------------------
INFO train_kitti_metric.py: 111:         GPU_num: 1                             
INFO train_kitti_metric.py: 112: train_data_size: 6345                          
INFO train_kitti_metric.py: 113:   val_data_size: 6345                          
INFO train_kitti_metric.py: 114: total_iterations: 95190                         
INFO net_tools.py:  38: loading checkpoint /media/wangxu/Data/Downloads/VNL/kitti_eigen.pth
Traceback (most recent call last):
  File "./tools/train_kitti_metric.py", line 141, in <module>
    val_dataloader, val_err, ignore_step)
  File "./tools/train_kitti_metric.py", line 23, in train
    for i, data in enumerate(train_dataloader):
  File "/media/wangxu/Data/Downloads/VNL/VNL_Monocular_Depth_Prediction-master/data/load_dataset.py", line 23, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/wangxu/software/anaconda3/envs/VNL/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/wangxu/software/anaconda3/envs/VNL/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/wangxu/software/anaconda3/envs/VNL/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangxu/software/anaconda3/envs/VNL/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/wangxu/Data/Downloads/VNL/VNL_Monocular_Depth_Prediction-master/data/kitti_dataset.py", line 35, in __getitem__
    data = self.online_aug_train(anno_index)
  File "/media/wangxu/Data/Downloads/VNL/VNL_Monocular_Depth_Prediction-master/data/kitti_dataset.py", line 67, in online_aug_train
    B_classes = self.depth_to_class(B_crop)
AttributeError: 'KITTIDataset' object has no attribute 'depth_to_class'
```

I used global search and found that there were no function 'depth_to_class' ,which is used in line 66 of kitti_dataset.py.
```
A_crop = A_crop.transpose((2, 0, 1))
B_crop = B_crop[np.newaxis, :, :]

# change the color channel, bgr->rgb
A_crop = A_crop[::-1, :, :]

# to torch, normalize
A_crop = self.scale_torch(A_crop, 255.)
B_crop = self.scale_torch(B_crop, resize_ratio)

**B_classes = self.depth_to_class(B_crop)**

invalid_side = [0, 0, 0, 0] if crop_size[1] != 0 else [int((pad[0] + 50)*resize_ratio), 0, 0, 0]
```

Could you give me some advice? Thank you so much!
PS:The version of my pytorch is 1.1.0

**Comment by YvanYin** [comment]
Sorry for the typo. Please use **  def depth_to_bins(self, depth):** at LN 182.
